name: Deploy BIN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_FRONT_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/GPS
            ./deploy_frontend.sh

      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_FRONT_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/GPS
            ./deploy_backend.sh
