name: Deploy BIN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_FRONT_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/frontend
            git fetch origin
            git reset --hard origin/main

      - name: Deploy Backend (via frontend)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_FRONT_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ssh -i /home/ubuntu/ssh-key-2026-03-13.key -o StrictHostKeyChecking=no ubuntu@10.0.2.8 << 'EOF'
            cd /var/www/html/backend/backend
            git fetch origin
            git reset --hard origin/main
            cp -r /var/www/html/backup/config .
            EOF
